### ISSUE TITLE
Explore 페이지에 Encoding 문제가 발생.

### ISSUE THREAD

**Issue by shin6949** [shin6949/capstone2#16]
Explore 페이지 접속시 Encoding 문제가 발생. 

---
## Error StackTrace
```
23:31:49 [http-nio-8080-exec-7] ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.StackOverflowError] with root cause
java.lang.StackOverflowError: null
	at com.cos.iter.domain.user.User.hashCode(User.java:28) ~[classes/:?]
	at com.cos.iter.domain.post.Post.hashCode(Post.java:33) ~[classes/:?]
	at com.cos.iter.domain.image.Image.hashCode(Image.java:10) ~[classes/:?]
``` 

위의 hashCode 에러가 지속적으로 반복 됨.

**Comment by shin6949** [comment]
93b1d8b Commit으로 해결 완료 됨.
Image Entity의 hashCode Error로 lombok에서 exclude 처리하여 해결함.
